name: Quick Test
on:
  push:
  pull_request_target:
    types: [labeled]
  
jobs:
  test-ia-scan:
    if: |
      github.event_name == 'push' ||
      github.event_name == 'schedule' ||
      (github.event_name == 'pull_request_target' &&
      github.event.label.name == 'ok-to-test')
    runs-on: ubuntu-latest
    permissions:
      # required for all workflows
      security-events: write
      # only required for workflows in private repositories
      actions: read
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create scan results directory
        run: mkdir ia-scan-results
      
      - name: Test basic image scan
        uses: ./
        with:
          falcon_client_id: ${{ vars.FALCON_CLIENT_ID }}
          falcon_region: ${{ vars.FALCON_CLOUD_REGION }}
          scan_type: image
          image: nginx:latest
          output_path: ia-scan-results/
          report_formats: sarif
          minimum_severity: medium
        env:
          FALCON_CLIENT_SECRET: ${{ secrets.FALCON_CLIENT_SECRET }}
      
      - name: Show scan results
        run: |
          ls -la ia-scan-results/
          echo "Looking for SARIF files..."
          find ia-scan-results/ -name "*.sarif" -type f || echo "No SARIF files found"
          if ls ia-scan-results/*.sarif 1> /dev/null 2>&1; then
            echo "SARIF file contents:"
            cat ia-scan-results/*.sarif
          else
            echo "No SARIF files found to display"
          fi

      - name: Upload sarif file
        uses: github/codeql-action/upload-sarif@v3
        if: always() && hashFiles('ia-scan-results/*.sarif') != ''
        with:
          sarif_file: ia-scan-results

  test-iac-scan:
    if: |
      github.event_name == 'push' ||
      github.event_name == 'schedule' ||
      (github.event_name == 'pull_request_target' &&
      github.event.label.name == 'ok-to-test')
    runs-on: ubuntu-latest
    name: Quick IaC Test
    permissions:
      # required for all workflows
      security-events: write
      # only required for workflows in private repositories
      actions: read
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create IaC scan results directory
        run: mkdir iac-scan-results
      
      - name: Test IaC scan
        uses: ./
        with:
          falcon_client_id: ${{ vars.FALCON_CLIENT_ID }}
          falcon_region: ${{ vars.FALCON_CLOUD_REGION }}
          scan_type: iac
          path: tests/
          output_path: iac-scan-results/
          report_formats: sarif
        env:
          FALCON_CLIENT_SECRET: ${{ secrets.FALCON_CLIENT_SECRET }}
      
      - name: Show scan results
        run: |
          ls -la iac-scan-results/
          echo "Looking for SARIF files..."
          find iac-scan-results/ -name "*.sarif" -type f || echo "No SARIF files found"
          if ls iac-scan-results/*.sarif 1> /dev/null 2>&1; then
            echo "SARIF file contents:"
            cat iac-scan-results/*.sarif
          else
            echo "No SARIF files found to display"
          fi

      - name: Upload sarif file
        uses: github/codeql-action/upload-sarif@v3
        if: always() && hashFiles('iac-scan-results/*.sarif') != ''
        with:
          sarif_file: iac-scan-results
